
test :
	perl -I/home/mdupont/projects/otrs/CVSREMOTE/otrs/ \
	     -I/home/mdupont/projects/otrs/git/public/otrs \
	     -I/home/mdupont/projects/otrs/CVSREMOTE/iPhoneHandle \
	     ./003_json_screen_config_new_phone.t